import Head from "next/head";
import Markdown from "react-markdown";
import about from "../markdown/about.md";
import schedule from "../markdown/schedule.md";
import programme from "../markdown/programme.md";
import tools from "../markdown/tools.md";
import log from "../markdown/log.md";
import Image from "next/image";
import { Noto_Sans_JP } from "next/font/google";
const notoSansJP = Noto_Sans_JP({
  weight: "400",
  display: "swap",
  preload: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <main className={notoSansJP.className}>
        <h1>
          <Image src={"/logo.png"} width={300} height={300} alt={"Togothon"} />
        </h1>
        <div className={"markdown"}>
          <section>
            <Markdown>{about}</Markdown>
          </section>
          <section>
            <Markdown>{schedule}</Markdown>
          </section>
          <section>
            <Markdown>{tools}</Markdown>
          </section>
          <section>
            <Markdown>{programme}</Markdown>
          </section>
          <section>
            <Markdown>{log}</Markdown>
          </section>
        </div>
      </main>
    </>
  );
}
